services:
  - type: web
    name: code2flowchart
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GOOGLE_API_KEY
        value: AIzaSyBg4RiH9FSdee42deOSCKRojaLgiuBky0Y
      - key: PORT
        value: 10000
      - key: FLASK_DEBUG
        value: false
